In [6]:
import numpy as np

a=np.array([[17,18,3,5,10],
            [5,16,8,9,11],
            [8,12,14,3,2],
            [18,19,4,6,5],
            [12,18,7,3,22]])
print(a)

b=int(input("Enter the row (0 to 4) : "))
c=int(input("Enter the column (0 to 4) : "))
print("\nValue : ",a[b,c])

n4=[]
if b+1<5:
    n4.append(a[b+1,c])
if b-1>=0:
    n4.append(a[b-1,c])
if c+1<5:
    n4.append(a[b,c+1])
if c-1>=0:
    n4.append(a[b,c-1])
print(f"N4 neighbours of {a[b,c]} : ",n4)

n8=[]
if b+1<5:
    n8.append(a[b+1,c])
if b-1>=0:
    n8.append(a[b-1,c])
if c+1<5:
    n8.append(a[b,c+1])
if c-1>=0:
    n8.append(a[b,c-1])
if b+1<5 and c+1<5:
    n8.append(a[b+1,c+1])
if b+1<5 and c-1>=0:
    n8.append(a[b+1,c-1])
if b-1>=0 and c+1<5:
    n8.append(a[b-1,c+1])
if b-1>=0 and c-1>=0:
    n8.append(a[b-1,c-1])
print(f"N8 neighbours of {a[b,c]} : ",n8)

nd=[]
if b+1<5 and c+1<5:
    nd.append(a[b+1,c+1])
if b+1<5 and c-1>=0:
    nd.append(a[b+1,c-1])
if b-1>=0 and c+1<5:
    nd.append(a[b-1,c+1])
if b-1>=0 and c-1>=0:
    nd.append(a[b-1,c-1])
print(f"Diagonal Neighbours of {a[b,c]} : ",nd)

[[17 18  3  5 10]
 [ 5 16  8  9 11]
 [ 8 12 14  3  2]
 [18 19  4  6  5]
 [12 18  7  3 22]]
Enter the row (0 to 4) : 2
Enter the column (0 to 4) : 1

Value :  12
N4 neighbours of 12 :  [19, 16, 14, 8]
N8 neighbours of 12 :  [19, 16, 14, 8, 4, 18, 8, 5]
Diagonal Neighbours of 12 :  [4, 18, 8, 5]


MY Method

In [8]:
import numpy as np

a=np.array([[17,18,3,5,10],
            [5,16,8,9,11],
            [8,12,14,3,2],
            [18,19,4,6,5],
            [12,18,7,3,22]])
print(a)

b=int(input("Enter the row (0 to 4) : "))
c=int(input("Enter the column (0 to 4) : "))
print("\nValue : ",a[b,c])

n4=[]
if b+1<5:
    n4.append(a[b+1,c])
if b-1>=0:
    n4.append(a[b-1,c])
if c+1<5:
    n4.append(a[b,c+1])
if c-1>=0:
    n4.append(a[b,c-1])
print(f"N4 neighbours of {a[b,c]} : ",n4)

nd=[]
if b+1<5 and c+1<5:
    nd.append(a[b+1,c+1])
if b+1<5 and c-1>=0:
    nd.append(a[b+1,c-1])
if b-1>=0 and c+1<5:
    nd.append(a[b-1,c+1])
if b-1>=0 and c-1>=0:
    nd.append(a[b-1,c-1])
print(f"Diagonal Neighbours of {a[b,c]} : ",nd)

n8=[]
n8=n4+nd
print(f"N8 neighbours of {a[b,c]} : ",n8)

[[17 18  3  5 10]
 [ 5 16  8  9 11]
 [ 8 12 14  3  2]
 [18 19  4  6  5]
 [12 18  7  3 22]]
Enter the row (0 to 4) : 2
Enter the column (0 to 4) : 1

Value :  12
N4 neighbours of 12 :  [19, 16, 14, 8]
Diagonal Neighbours of 12 :  [4, 18, 8, 5]
N8 neighbours of 12 :  [19, 16, 14, 8, 4, 18, 8, 5]
